\set SHAPP_PASSWORD `echo $SHAPP_PWORD`
CREATE USER shapp WITH LOGIN PASSWORD :'SHAPP_PASSWORD';

create database speedhog OWNER shapp;
GRANT ALL PRIVILEGES ON DATABASE speedhog TO shapp;
\c speedhog
create schema sh AUTHORIZATION shapp;
SET search_path TO sh;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sh TO shapp;
GRANT SELECT ON ALL TABLES IN SCHEMA sh TO shapp;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA sh TO shapp;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA sh TO shapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA sh GRANT ALL PRIVILEGES ON TABLES TO shapp;
